config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  resources :users, only: [:new, :create, :destroy, :show] do
    resources :reservations
  end

  resources :restaurants do
    resources :reservations
  end

  resources :sessions

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  validate :check_availability


  def check_availability
    unless restaurant.available?(self.seats, self.reservation_time)
      errors.add(:base, "We're sorry, there are no available seats at that time.")
    end
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  has_many :reservations
  has_many :users, through: :reservations


  # before_action :available?

  # def available?(party_size)
  #
  # end


  def available?(seats, date_time)
    bookedSeats = self.reservations.where(reservation_time: date_time).sum(:seats)
    available_capacity = self.capacity - bookedSeats
    return available_capacity >= seats
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reservations
  has_many :owned_restaurants, class_name: Restaurant
  has_many :restaurants, through: :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :gravatar_for

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please Log in"
      redirect_to new_sessions_path
    end
  end

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    @gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :load_restaurant
  before_action :current_user

  def new
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user_id = @current_user[:id]

    if @reservation.save
      redirect_to user_url(@current_user), notice: "Reservation Successful!"
    else
      puts @reservation.errors.full_messages
      render 'restaurants/show'
    end
  end

  def destroy
  end

  def show
  end

  def edit
  end

  private
  def reservation_params
    params.require(:reservation).permit(:reservation_time, :seats, :user_id)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end



    # available_capacity = @restaurant.capacity - @restaurant.reservations.sum(:seats)
    # puts @restaurant.capacity
    # puts @restaurant.reservations.sum(:seats)
    # puts available_capacity
    # puts "________________________________"


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :show]
  before_action :current_user
  before_action :load_restaurant, only: [:show, :destroy, :edit]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = @current_user.owned_restaurants.create(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_url(@restaurant), Notice: "Restaurant Created Successfully!"
    else
      render :new
    end
  end

  def show
    @reservation = Reservation.new
  end

  def destroy
  end

  def edit
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :description, :picture_url, :capacity, :email)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_logged_in, except: :destroy

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In!"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :destroy]
  before_action :ensure_logged_in, only: [:show, :destroy]


  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      redirect_to new_session_url, notice: "Sign Up Successful - Please Login"
    else
      render :new
    end
  end

  def show
    gravatar_for(@user)

  end

  def destroy
    @user.destroy
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :owner, :password, :password_confirmation)
  end

  def load_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seatyourself</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">

      <div id="nav" class="u-full-width">
        <%= link_to "HomePage", root_path, class: "button u-pull-left" %>
        <% if current_user == nil %>
            <p>
              <%= link_to "Log in", new_session_path, class: "button" %><%= link_to "Sign up", new_user_path,
                                                                                       class: "button" %>
            </p>

        <% elsif current_user.owner == 0 %>
            <p>
              <%= link_to "User Profile", user_path(current_user), class: "button" %>
            </p>
        <% else current_user.owner == 1 %>
            <p>
              <%= link_to "Add Restaurant", new_restaurant_path, class: "button"%><%= link_to "Owner Profile", user_path(current_user), class: "button"%>
            </p>
        <% end %>
      </div>

      <div class="six columns">
        <% if flash[:notice] %>
            <p id="notice"><%= flash[:notice] %></p>
        <% end %>

        <% if flash[:alert] %>
            <p id="alert"><%= flash[:alert] %></p>
        <% end %>
      </div>

      <%= yield %>

      <footer class="u-full-width">
        <p class="userinfo">
          <% if current_user %>
              <strong>Signed in as <%= current_user.first_name%>. <%= link_to "Log out", session_path("current"),
                                                                           :method =>
            :delete%></strong>
          <% else %>

          <% end %>
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |f| %>
  <div class="six columns">
    <%= f.label :reservation_time, "Reservation Time" %>
    <%= f.datetime_select :reservation_time, :default =>{:minute => 0}, :discard_minute => true %>
  </div>

  <div class="six columns">
    <%= f.label :seats, "How Many Seats?" %>
    <%= f.number_field :seats%>
  </div>

  <div class="six columns">
    <%= f.submit "Request", class: "button-primary"%>
  </div>

<% end %>

app/views/reservations/create.html.erb
<div class="six columns">
  <h3>Reservations#create</h3>
  <p>Find me in app/views/reservations/create.html.erb</p>
</div>

app/views/reservations/edit.html.erb
<div class="six columns">
  <h3>Reservations#edit</h3>
  <p>Find me in app/views/reservations/edit.html.erb</p>
</div>

app/views/reservations/new.html.erb
<div class="six columns">
  <h3>Reservations#new</h3>
  <p>Find me in app/views/reservations/new.html.erb</p>
</div>

app/views/reservations/show.html.erb
<div class="six columns">
  <h3>Reservations#show</h3>
  <p>Find me in app/views/reservations/show.html.erb</p>
</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

    <div class="six columns">
      <%= f.label :name %>
      <%= f.text_field :name, class: "u-full-width" %>
    </div>

    <div class="six columns">
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: "u-full-width" %>
    </div>

    <div class="six columns">
      <%= f.label :capacity %>
      <%= f.text_field :capacity, class: "u-full-width" %>
    </div>

    <div class="six columns">
      <%= f.label :picture_url %>
      <%= f.text_field :picture_url, class: "u-full-width" %>
    </div>

    <div class="six columns">
      <%= f.label :address %>
      <%= f.text_area :address, class: "u-full-width" %>
    </div>

    <div class="six columns">
      <%= f.label :description %>
      <%= f.text_area :description, class: "u-full-width" %>
    </div>

    <div class="six columns">
      <div class="button-primary">
        <%= f.submit %>
      </div>
    </div>


<% end %>

app/views/restaurants/edit.html.erb
<div class="six columns">
  <h3>EditRestaurant</h3>
</div>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<div class="u-full-width">
  <h3>Restaurants</h3>

  <% @restaurants.each do |restaurant| %>

      <div class="listing">
        <img id="main_picture" src="<%= restaurant.picture_url %>" alt="">
        <div class="address">
          <h6><%= link_to restaurant.name, restaurant_path(restaurant)%></h6>
          <p><%= restaurant.address %></p>
        </div>
        <div class="description">

          <p>
            <%= restaurant.description %>
          </p>
        </div>
      </div>
  <% end %>


</div>

app/views/restaurants/new.html.erb
<div class="six columns">
  <h3>Add Restaurant</h3>
</div>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="six columns">
  <h3><%= @restaurant.name %></h3>

  <p>
    <img src="<%=@restaurant.picture_url%>" alt="">
  </p>

  <p>
    Phone: <%= number_to_phone(@restaurant.phone) %>
  </p>

  <p>
    Address: <%= @restaurant.address %>
  </p>

  <p>
    Description: <%= @restaurant.description %>
  </p>

  <p>
    Capacity: <%= @restaurant.capacity %>
  </p>
</div>


<% if current_user %>
  <div id="reservation">
    <%= render 'reservations/form' %>
  </div>
<% else %>
  <div class="six columns">
    <strong>Please <%= link_to "Log in", new_session_path%> or <%= link_to "Sign Up", new_user_path%> to make a
    reservation.</strong>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="six columns">
  <h4>please sign up below.</h4>
</div>

<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is Invalid</h2>
          <ul>
            <%= @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="six columns">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="six columns">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="six columns">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="six columns">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="six columns">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="six columns">
      <p>
        <%= f.label :owner, :style => "float:left;" %>
        <%= f.radio_button(:owner, 1)%>
      </p>
      <p>
        <%= f.label :Patron, :style => "float:left;" %>
        <%= f.radio_button(:owner, 0)%>
      </p>
    </div>

    <div class="six columns">
      <%= f.submit class: "button-primary" %>
    </div>

<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="u-full-width">
  <img id="profile" src="<%= gravatar_for(@current_user) %>" alt="">
  <h4><%= current_user.first_name %></h4>
</div>




  <% if @user.owner == 1 %>
    <div id="users_restaurants" class="six columns u-pull-left">
      <h4>Restaurants</h4>
      <% @user.owned_restaurants.each do |restaurant|  %>
        <p>
          <%= restaurant.name %>
        </p>
      <% end %>
    </div>

    <div class="six columns u-pull-right">
      <h4>Reservations</h4>
      <% @user.reservations.each do |reservation| %>
          <p>
            <%= Restaurant.find(reservation[:restaurant_id]).name %>
          </p>

          <p>
            Time: <%= reservation.reservation_time %>
          </p>

          <p>
            Seats: <%= reservation.seats%>
          </p>
      <% end %>
    </div>

    <% else %>
      <div class="six columns u-pull-left">
        <h4>Reservations</h4>
        <% @user.reservations.each do |reservation| %>
            <p>
              <%= Restaurant.find(reservation[:restaurant_id]).name %>
            </p>

            <p>
              Time: <%= reservation.reservation_time %>
            </p>

            <p>
              Seats: <%= reservation.seats%>
            </p>

        <% end %>
      </div>

    <% end %>